TABLE_SCHEMAS = {
    "respondentes": """
        CREATE TABLE IF NOT EXISTS respondentes (
            id_respondente TEXT PRIMARY KEY,
            id_original TEXT,
            row_index INTEGER
        )
    """,
    "preguntas": """
        CREATE TABLE IF NOT EXISTS preguntas (
            pregunta_id TEXT PRIMARY KEY,
            seccion TEXT,
            numero_pregunta TEXT,
            texto_pregunta TEXT,
            tipo_pregunta TEXT,
            tipo_calculo TEXT,
            base_valida TEXT,
            regla_transformacion TEXT,
            usar_en_dashboard INTEGER,
            orden_cuestionario REAL,
            seccion_cuestionario TEXT,
            bloque_cuestionario TEXT,
            grupo_menu_reporteador TEXT,
            mostrar_en_menu_reporteador TEXT,
            prioridad_reporteador TEXT
        )
    """,
    "variables": """
        CREATE TABLE IF NOT EXISTS variables (
            variable TEXT PRIMARY KEY,
            label TEXT,
            tipo_spss TEXT,
            pregunta_id TEXT,
            tipo_pregunta TEXT,
            clasificacion_analitica TEXT,
            usar_en_dashboard INTEGER,
            es_banner INTEGER,
            es_filtro INTEGER,
            es_ponderador INTEGER,
            tipo_calculo TEXT,
            n_validos INTEGER,
            n_missing INTEGER,
            valores_unicos INTEGER,
            min REAL,
            max REAL,
            es_banner_recomendado INTEGER,
            es_filtro_recomendado INTEGER,
            nivel_relevancia_comercial TEXT,
            justificacion_banner_filtro TEXT,
            uso_comercial_sugerido TEXT,
            distribucion_base TEXT,
            riesgo_uso_analitico TEXT,
            requiere_factor INTEGER,
            tipo_factor_recomendado TEXT,
            variables_para_factor TEXT,
            regla_factor_sugerida TEXT,
            justificacion_factor TEXT,
            prioridad_factor TEXT,
            grid_id TEXT,
            pregunta_padre TEXT,
            tipo_estructura_grid TEXT,
            es_grid INTEGER,
            es_item_grid INTEGER,
            es_grid_rm_loop INTEGER,
            orden_fila_grid REAL,
            texto_fila_grid TEXT,
            entidad_loop TEXT,
            orden_entidad_loop REAL,
            label_entidad_loop TEXT,
            codigo_opcion_rm TEXT,
            label_opcion_rm TEXT,
            orden_opcion_rm REAL,
            formato_rm TEXT,
            value_label_patron TEXT,
            valores_observados_patron TEXT,
            es_abierta_asociada INTEGER,
            base_valida_pregunta_padre REAL,
            base_valida_fila REAL,
            base_valida_columna REAL,
            regla_base_valida TEXT,
            metrica_grid_recomendada TEXT,
            regla_tabular_recomendada TEXT,
            riesgo_grid TEXT,
            match_confianza TEXT,
            mostrar_en_menu_reporteador TEXT
        )
    """,
    "respuestas_grid_loop": """
        CREATE TABLE IF NOT EXISTS respuestas_grid_loop (
            id_respondente TEXT,
            pregunta_id TEXT,
            grid_id TEXT,
            variable TEXT,
            entidad_loop TEXT,
            orden_entidad_loop REAL,
            codigo_opcion TEXT,
            label_opcion TEXT,
            orden_opcion REAL,
            valor TEXT,
            seleccionado INTEGER,
            base_valida INTEGER,
            missing_estructural INTEGER,
            peso REAL
        )
    """,
    "grids": """
        CREATE TABLE IF NOT EXISTS grids (
            grid_id TEXT PRIMARY KEY,
            pregunta_padre TEXT,
            texto_pregunta TEXT,
            tipo_grid TEXT,
            tipo_estructura_grid TEXT,
            es_grid_rm_loop INTEGER,
            tipo_escala_columnas TEXT,
            codigos_columnas_grid TEXT,
            labels_columnas_grid TEXT,
            metrica_grid_recomendada TEXT,
            regla_tabular_recomendada TEXT,
            requiere_factor INTEGER,
            tipo_factor_recomendado TEXT,
            regla_factor_sugerida TEXT,
            riesgo_grid TEXT
        )
    """,
    "grid_items": """
        CREATE TABLE IF NOT EXISTS grid_items (
            grid_id TEXT,
            variable TEXT,
            orden_fila_grid REAL,
            texto_fila_grid TEXT,
            entidad_loop TEXT,
            codigo_opcion_rm TEXT,
            label_opcion_rm TEXT,
            formato_rm TEXT,
            rango_esperado TEXT,
            rango_observado TEXT,
            value_labels_compartidos TEXT,
            patron_label_constante TEXT,
            match_grid TEXT,
            evidencia_grid TEXT,
            PRIMARY KEY (grid_id, variable)
        )
    """,
    "configuracion_dashboard": """
        CREATE TABLE IF NOT EXISTS configuracion_dashboard (
            tipo_configuracion TEXT,
            variable TEXT,
            pregunta_id TEXT,
            label TEXT,
            es_recomendado INTEGER,
            es_banner_recomendado INTEGER,
            es_filtro_recomendado INTEGER,
            prioridad TEXT,
            nivel_relevancia_comercial TEXT,
            justificacion TEXT,
            justificacion_banner_filtro TEXT,
            uso_comercial_sugerido TEXT,
            distribucion_base TEXT,
            riesgo_uso_analitico TEXT,
            fuente_hoja TEXT
        )
    """,
    "recomendaciones_reporteador": """
        CREATE TABLE IF NOT EXISTS recomendaciones_reporteador (
            tipo_recomendacion TEXT,
            variable TEXT,
            variable_label TEXT,
            pregunta_id TEXT,
            numero_pregunta TEXT,
            texto_pregunta TEXT,
            seccion_cuestionario TEXT,
            rol_recomendado TEXT,
            es_banner_recomendado INTEGER,
            es_filtro_recomendado INTEGER,
            nivel_relevancia_comercial TEXT,
            justificacion TEXT,
            uso_comercial_sugerido TEXT,
            distribucion_base TEXT,
            riesgo_uso_analitico TEXT,
            requiere_factor INTEGER,
            tipo_factor_recomendado TEXT,
            variables_para_factor TEXT,
            regla_factor_sugerida TEXT,
            justificacion_factor TEXT,
            prioridad_factor TEXT,
            fuente_hoja TEXT
        )
    """,
}


EXPECTED_TABLES = [
    "respondentes",
    "preguntas",
    "variables",
    "opciones",
    "respuestas_long",
    "multirrespuesta_long",
    "respuestas_grid_loop",
    "escalas_long",
    "abiertas",
    "riesgos",
    "grids",
    "grid_items",
    "estructuras_detectadas",
    "configuracion_dashboard",
    "recomendaciones_reporteador",
    "factores_configurados",
]
