from __future__ import annotations

from src.analytics_core.interface import AnalyticsCore, AnalyticsRequest
from src.analytics_core.legacy_adapter import LegacyAdapter
from src.analytics_core.mode import (
    ANALYTICS_ENGINE_ENV_VAR,
    ExecutionModeError,
    resolve_execution_mode,
)
from src.analytics_core.runner import generate_report
from src.analytics_core.significance import (
    ENGINE_VERSION as SIGNIFICANCE_ENGINE_VERSION,
    ProportionComparisonInput,
    ProportionFamilyRequest,
    SignificanceExecutionError,
    execute_proportion_family,
)
from src.analytics_core.results import (
    CANONICAL_RESULT_SCHEMA_VERSION,
    CANONICAL_RESULTS_RULES_VERSION,
    assemble_canonical_result,
    base_from_ledger,
    compare_legacy_canonical_result,
    make_request_snapshot,
    make_slice,
    qa_event,
    qa_events_from_envelope,
    significance_state_for_request,
    transport_significance,
    value_and_qa_from_formula,
    value_from_formula,
)
from src.analytics_core.serialization import (
    from_canonical_data,
    from_canonical_json,
    to_canonical_data,
    to_canonical_json,
)
from src.analytics_core.universe import (
    LegacyUniverseComparison,
    LegacyUniverseComparisonStatus,
    ResponseState,
    UniverseEvaluationContext,
    UniverseEvaluationError,
    UniverseEvaluationResult,
    UniverseEvaluationStatus,
    UniverseEvaluator,
)
from src.analytics_core.weights import (
    LEGACY_CANONICAL_INTENDED_B1_CHANGE,
    LEGACY_CANONICAL_LEGACY_DEFECT_REPRODUCED,
    LEGACY_CANONICAL_M2_BASE_DIFFERENCE,
    LEGACY_CANONICAL_PARITY,
    LEGACY_CANONICAL_POTENTIAL_REGRESSION,
    LEGACY_CANONICAL_PRESENTATION_ONLY,
    LEGACY_CANONICAL_UNSUPPORTED_V1,
    RESOLUTION_ANALYSIS_OVERRIDE,
    RESOLUTION_NONE,
    RESOLUTION_PROJECT_DEFAULT,
    WEIGHT_RUNTIME_RULES_VERSION,
    LegacyCanonicalWeightComparison,
    WeightDistributionDiagnostics,
    WeightEvaluationContext,
    WeightEvaluationResult,
    WeightProvenance,
    WeightQA,
    WeightResolution,
    compare_legacy_canonical_weight_result,
    evaluate_weighted_base,
    resolve_active_weight,
)

__all__ = [
    "ANALYTICS_ENGINE_ENV_VAR",
    "AnalyticsCore",
    "AnalyticsRequest",
    "CANONICAL_RESULT_SCHEMA_VERSION",
    "CANONICAL_RESULTS_RULES_VERSION",
    "ExecutionModeError",
    "LegacyAdapter",
    "LegacyUniverseComparison",
    "LegacyUniverseComparisonStatus",
    "LegacyCanonicalWeightComparison",
    "LEGACY_CANONICAL_INTENDED_B1_CHANGE",
    "LEGACY_CANONICAL_LEGACY_DEFECT_REPRODUCED",
    "LEGACY_CANONICAL_M2_BASE_DIFFERENCE",
    "LEGACY_CANONICAL_PARITY",
    "LEGACY_CANONICAL_POTENTIAL_REGRESSION",
    "LEGACY_CANONICAL_PRESENTATION_ONLY",
    "LEGACY_CANONICAL_UNSUPPORTED_V1",
    "RESOLUTION_ANALYSIS_OVERRIDE",
    "RESOLUTION_NONE",
    "RESOLUTION_PROJECT_DEFAULT",
    "ResponseState",
    "UniverseEvaluationContext",
    "UniverseEvaluationError",
    "UniverseEvaluationResult",
    "UniverseEvaluationStatus",
    "UniverseEvaluator",
    "WEIGHT_RUNTIME_RULES_VERSION",
    "WeightDistributionDiagnostics",
    "WeightEvaluationContext",
    "WeightEvaluationResult",
    "WeightProvenance",
    "WeightQA",
    "WeightResolution",
    "assemble_canonical_result",
    "base_from_ledger",
    "compare_legacy_canonical_weight_result",
    "compare_legacy_canonical_result",
    "execute_proportion_family",
    "evaluate_weighted_base",
    "from_canonical_data",
    "from_canonical_json",
    "generate_report",
    "ProportionComparisonInput",
    "ProportionFamilyRequest",
    "make_request_snapshot",
    "make_slice",
    "qa_event",
    "qa_events_from_envelope",
    "resolve_active_weight",
    "resolve_execution_mode",
    "significance_state_for_request",
    "SignificanceExecutionError",
    "SIGNIFICANCE_ENGINE_VERSION",
    "to_canonical_data",
    "to_canonical_json",
    "transport_significance",
    "value_and_qa_from_formula",
    "value_from_formula",
]
